Remove 4th argument from builders.forInStatement call.
This silences the following TypeScript error:

  test/printer.ts:410:16 - error TS2554: Expected 3 arguments, but got 4.

which was a direct consequence of this PR to remove old Mozilla and E4X
specific AST definitions from ast-types: https://github.com/benjamn/ast-types/pull/303

@brieb This bug would have totally gone unnoticed if you hadn't converted
ast-types to TypeScript!